### ISSUE TITLE
particle distribution for vector operations

### ISSUE THREAD

**Issue by Gorkowski** [uncscode/particula#126]
The current way particle class is setup does not scale for a large number (>10000) of particles interacting, like via coagulation with unit tracking.

I want to have a vectorized (numpy array) of the particles, that can be used with the vectorized utilities in development. 

I used to do an array of particle objects (see old parcel class), this was very slow for coagulation calculations. 100 particles coagulating to 1 particle took 10 seconds to calculate. 

After this vectorized class, then we can address an updated parcel and time-stepping. We can add units back in as well.

**Comment by ngam** [comment]
I think this is done now, right? Feel free to reopen if not
