### ISSUE TITLE
constructing coagulation "kernel"

### ISSUE THREAD

**Issue by ngam** [uncscode/particula#131]
Calculation should be flexible enough such that, in the order of importance:
1. for radius_1 = numpy.array of size (N, 1) and radius_2 - numpy.array of size (M, 1), the coagulation kernel is a numpy.array of size (N, M)
2. in theory, (N, M) could be extended to (N, M, X, Y) to account for X and Y charge matrices on each radius_1 and radius_2, but it is more efficient to construct wrappers such that kernel (N, M) is repeated to account for permutation of cases

For 1., we actually only need the half of that block since it is completely symmetric (by definition, radius_1 x radius_2 == radius_2 x radius_1)

For 2., in reality, the permutations are relatively few, e.g. 
1. radius_1_pos x radius_2_neg ==  radius_1_neg x radius_2_pos == radius_2_pos x radius_1_neg == radius_2_neg x radius_1_pos
2. coagulation between +5 and +5 is quite close to zero except in when charge is "screened"
3. charge is "screened" relatively quickly and we could impose asymptotes if we hit computational limits
4. the maximum realistic charges in the atmosphere scale with size, e.g. 
    1. less than 10 nm, at most one charge
    2. less than 100 nm, at most a few charges
    3. less than 1000 nm, at most ~10 charges (noting that coagulation calculation becomes significantly easier and cheaper as size grows)

**Comment by ngam** [comment]
In practice, we need the following:
1. constructing numpy.arrays (actually, pint does that already!)
2. whenever multiplying/adding radius, we should do radius * radius' or radius + radius' (utilizing auto broadcasting, a_radius(1,M) + b_radius(N,1) = c_radius(N,M)
3. write tests to ensure all's smooth and nothing nonsensical is going on (e.g. conservation, symmetry, etc. checks can go a long way)

**Comment by ngam** [comment]
I think we ought to firmly decide this at the outset. We need to decide our privileged dimensions. 

I say the most important dimension is size, this means radius can be allowed to be a a scalar, list, or numpy.array (yield same behavior). So this is a one-dimensional array (vector), let's give it X elements.

Then, we have to allow the "other_radius" Y elements (in reality often, it would be also X, but let's be flexible).

For @Gorkowski, we need to be flexible about height, temperature, and pressure (these are only variable really since they depend on each other, or we can simply approximate them as such --- I don't want to keep adding dimensions). Let's give this Z elements. 

This means, we are going to un-privilege charge, and any calculation will have to be repeated for charges. This is okay as I explain above. Otherwise we would need to have two more dimensions (C1, C2) for charge and other_charge. 

in ngam:ffwd, I have implemented two dimensions for now: (X, Y) and (X, Z), but not (X, Y, Z) yet because I need to figure out a way to effectively broadcast the Z dimension when already broadcasting X and Y. This comes up in calculating coagulation, so I am throwing errors for now:

```py
        if np.array(self.temperature.m).size > 1:
            raise ValueError(
                f"\t\n"
                f"\tTemperature {self.temperature} must be scalar for this!\n"
                f"\tThis is to allow calculation of the coagulation kernel.\n"
                f"\tYou can repeat this routine for different temperatures."
            )

        if np.array(
            self.charge.m
        ).size + np.array(self.other_charge.m).size > 2:
            raise ValueError(
                f"\t\n"
                f"\t Charges {self.charge} and {self.other_charge} must\n"
                f"\tbe scalars for this to work!\n"
                f"\tYou can repeat this routine for different charges."
            )

```

**Comment by ngam** [comment]
@Gorkowski how soon do you anticipate needing a variable height/temperature/pressure?

**Comment by Gorkowski** [comment]
I see your point on the extra dimensions. @ngam 

1) We could always have a detailed and slow option that calculated the kernel new each time it is called.
2) What do we think the error would be in the kernel for a 1000 mbar vs 700, to 300 mbar ?
3) Some sort of dynamic method where if the error is going to be >X then calculate the kernel, if <X use the precalculated 1000 mbar value even if the pressure is 950 mbar.

**Comment by ngam** [comment]
I think it shouldn't be too hard to add a temperature dimensions... I will need to think about that a little more
