### ISSUE TITLE
Test issue to practice contribution workflow

### ISSUE THREAD

**Issue by aktwo** [uncscode/particula#14]
I'm going to make a small change to try things out!

**Comment by ngam** [comment]
- assign the issue to yourself
- do something in our webpage in /docs 👀

**Comment by aktwo** [comment]
Wow, 5 minute response!

**Comment by ngam** [comment]
Not sure if that's good or bad... 🔮

**Comment by aktwo** [comment]
:)

Also, want to try adding a comment on my commit asking me to change something?
