### ISSUE TITLE
proposal to remove aerosol_dynamics folder

### ISSUE THREAD

**Issue by ngam** [uncscode/particula#140]
now we have the following structure:

particula. ... (`__init__.py`, `constants.py`, etc.)
particula.tests. ... (e.g. `constants_test.py`)
particula.util. ... (e.g. `util_x.py`)
particula.util.tests. ... (e.g. `util_x_test.py`)
particula.aerosol_dynamics. ... (e.g. `particle.py`)
particula.aerosol_dynamics.tests. ... (e.g. `particle_test.py`)

I propose to move everything from aerosol_dynamics to particula:

particula. ... (`__init__.py`, `constants.py`, `particle.py`, etc.)
particula.tests. ... (e.g. `constants_test.py`, `particle_test.py`)
particula.util. ... (e.g. `util_x.py`)
particula.util.tests. ... (e.g. `util_x_test.py`)

Thoughts?

**Comment by Gorkowski** [comment]
yeah, I think that makes sense....as particula==aerosol_dynamics. Or at least right now that is the case

**Comment by ngam** [comment]
Yeah and I don't think that would change. We can always add more chemistry, etc. and we can just add it under particula
