### ISSUE TITLE
add a proper solver

### ISSUE THREAD

**Issue by ngam** [uncscode/particula#142]
need two types of solvers in general:
1. simple time-based ODE solvers
2. a more complicated PDE solver for the GDE

**Comment by ngam** [comment]
Two options:
1. use an optimized ODE solver from numpy/scipy after converting PDE to ODEs
2. write a simple balance law solver utilizing numpy.arrays

**Comment by Gorkowski** [comment]
what did you think of scipy options, scipy.integrate.solve_ivp
https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html#scipy.integrate.solve_ivp

**Comment by ngam** [comment]
they are all ODE solvers... I believe we should just make our own solver. I can just copy my older solvers. The annoying  part is that they're going to be slower than whatever scipy or others have already cooked up... (the nearest to our specific application would be clawpack btw)

Without condensation, an ODE solver is okay. With condensation, more work is needed. See the beginning of a gimmicky way to transform our PDE into ODEs in this branch, ngam:issue142

https://github.com/ngam/particula/blob/issue142/particula/util/moc_odes.py

https://github.com/ngam/particula/blob/9b9920394a05f56849d2ed7e3f99dc34c19af562/particula/util/moc_odes.py#L1-L34

this type of stuff will work to an extent... and we may be able to pull it off quite spectacularly, but I need to think through it a little more carefully...

**Comment by ngam** [comment]
All our stuff will be of the form:

∂n/∂t + f(t,d,n) ∂n/∂d = g(t,d,n)

where f(t,d,n) is condensation flux and g(t,d,n) are all sinks and sources (coagulation, condensation loss, nucleation, etc. etc.)

Note ∂: it is definitely partial stuff here. The original equation would look something like this:
∂n/∂t + ∂(f(t,d,n)*n)/∂d = g(t,d,n), so condensation is a bit linked to n. 

d is the size in the above.

**Comment by ngam** [comment]
If I can convince myself that I am doing this correctly, then I will use scipy's functions to solve:
```
    MEANING: simultaneously solve
    1. d(radius)/d(time) = f(radius,time,denisty) with radius(0) = d0
    2. d(density)/d(time) = g(radius,time,density) with density(0) = n0(d0)
```
together. Note the "radius" above is FAKE radius as it's allowed to move in time. So it will be discarded and we would always anchor ourselves back to d0 (the original size).

Anyway, I just need to write up a few simple examples of this to see it working correctly. Then I can pursue it. IF this doesn't work, we will have a customized PDE solver very quickly. I am just trying to take my time and not rush this. Hopefully by the weekend I will push one or the other...

**Comment by ngam** [comment]
The drawback of using a customized solver is going to be the for loop. I have no idea how to accelerate beyond it besides using jit/numba/etc. But that's relatively minor --- inside the loop things will be quite fast. I will give it a go and see how things turn out soon-ish

**Comment by ngam** [comment]
I also need to document this stuff. I worked A LOT back in the day on the math theory of this, and so I need to make sure I am being reasonable in terms of accuracy vs speed, etc. etc.
