### ISSUE TITLE
Investigate mamba package manager

### ISSUE THREAD

**Issue by aktwo** [uncscode/particula#16]
We currently use conda and maybe we should consider using mamba alongside/instead.

https://github.com/mamba-org/mamba

**Comment by ngam** [comment]
I have been playing around with mamba and doing a fair bit of experimenting with building packages, e.g. see [here](anaconda.org/ngam); also [uncscode's channel](anaconda.org/uncscode)!. Anyway, my experience with mamba so far is thus:
- _significantly_ faster than conda as advertised; and
- still in-preview-ish and in-dev, meaning it **fails** significantly more often than I would tolerate.

In sum, mamba is really good for a tidy set of packages or a few related packages, which will likely be our case for a while and maybe forever --- I would love to have our sole dependency be `numpy`!

**Comment by ngam** [comment]
Closing, I am adopting mamba as my personal default instead of conda --- once we have enough work, we can revisit this.
