### ISSUE TITLE
musica --- competitor alert ❗ 

### ISSUE THREAD

**Issue by ngam** [uncscode/particula#17]
(Multi-Scale Infrastructure for Chemistry and Aerosols)
https://journals.ametsoc.org/view/journals/bams/101/10/bamsD190331.xml

- [ ] figure out any source code around
- [ ] read more about implementation 
- [ ] they say "next-gen" --- what is current-gen and prev-gen?
- [ ] they say forward model, any inverse strategies?

**Comment by ngam** [comment]
https://github.com/NCAR/music-box

**Comment by ngam** [comment]
https://wiki.ucar.edu/display/MUSICA/MUSICA+Home

**Comment by ngam** [comment]
CONCLUSION: DOA.

**Comment by wkchuang** [comment]
> 
> 
> CONCLUSION: DOA.

What do you mean by DOA here @ngam ? They're no longer working on it?

**Comment by ngam** [comment]
@wkchuang --- no, quite the opposite. I suspect this is going to be the future of the unified scheme across the US Gov (coincidentally, after seeing this pkg, I heard passive internal discussions about it and other projects across NOAA). I say DOA, because I think this effort is only somewhat usable and valuable for global models, which are grossly averaged etc. and I am not a fan of that type of approach in general (despite usefulness) and I wouldn't want to replicate it here. We still should pay close attention to it as it will likely be the forefront of the established efforts at the global scale for the next ~10 years or so. Also well-funded and well-backed.
