### ISSUE TITLE
doi release

### ISSUE THREAD

**Issue by ngam** [uncscode/particula#228]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ngam** [comment]
@aktwo @wkchuang @Gorkowski I am planning to issue a doi for our repo and make it citable. I would like to do this quite soon (i.e. by mid June) because I have used various parts of the code to calculate some values going into a paper and I would like to cite this code here. Are you all okay with being listed as author of this repo irl? Later, we will write our own "model development" paper on this, but only when we get to a stable-ish release.

**Comment by aktwo** [comment]
Sorry for the late reply! That sounds fine to me.

**Comment by ngam** [comment]
No problem. I set up an automated Zenodo repo that will basically initiate a new DOI for each release starting with v0.0.5: https://zenodo.org/record/6634654

I need to figure out how to cite this correctly. For now, as long as we have a DOI, I am fine with it. But further tweaking may be necessary

**Comment by ngam** [comment]
I will get everything organized better once we reach a stable-ish release (either 0.1.0 or 1.0.0, likely the former). For now, I am pretty loose with how things go and happy to adapt and discuss strategies. 

Later in the summer, once I exhaust all my "already-coded" material (i.e. stuff I have done one form or another in the past), I will start writing a draft for a model development paper. That will be a good way to more rigorously document the work, but also provide us with the obvious doors/ways to keep going forward. Stay tuned!
