### ISSUE TITLE
Consider using pytype or something similar for static analysis

### ISSUE THREAD

**Issue by aktwo** [uncscode/particula#3]
https://github.com/google/pytype

Some other options: https://www.infoworld.com/article/3575079/4-python-type-checkers-to-keep-your-code-clean.html

**Comment by wkchuang** [comment]
I read through the link and came out feeling agnostic on the options. Seems like the important part is simply using one. I'm up for going with pytype, if it also means we (meaning @aktwo) have better knowledge of how it works.

**Comment by ngam** [comment]
@aktwo @wkchuang I assume we didn't incorporate this and #4 in the current pr (#27), right? We can probably address both this and #4 in a future housekeeping pr or something. 

Thanks again for the good hard work getting us started with a nice structure 🥇

**Comment by wkchuang** [comment]
We incorporated some of this in pr #27 , where at the end of the first line of a function definition, we include a ` -> float` or something similar, to check for typing.
