### ISSUE TITLE
fix code to satisfy github action workflow

### ISSUE THREAD

**Issue by ngam** [uncscode/particula#33]
the automated github action workflow in #32 will likely fail. Consider fixes to make all checks pass and have it become a standard for any future prs. 

Paging @wkchuang to help me with this.

**Comment by ngam** [comment]
Thanks @wkchuang for the merge!

See the errors in here: https://github.com/uncscode/particula/runs/4499831597?check_suite_focus=true

Next:

- [ ] determine which of them to fix and which to override
- [ ] set up more testing and sync with pr (i.e. make pr merge contingent on passing test suite)
- [ ] improve documentation and page build

**Comment by wkchuang** [comment]
Thanks @ngam , I've come across the issue of importing modules while trying to run files. The way it is written now works when running pytest, but doesn't work when running python.

I found this proposed solution https://stackoverflow.com/questions/48973742/proper-relative-imports-unable-to-import-module . I don't know how well it works, but perhaps you can take a look and give some of your thoughts.
