### ISSUE TITLE
deal with scipy deprecations 

### ISSUE THREAD

**Issue by mahf708** [uncscode/particula#496]
we currently require scipy <1.14 because scipy 1.14 changes the trapz semantics from trapz to trapezoid. However, fixing our code won't be enough because pymiescattering pkg seems out of date in terms of requiring a fix

cc @Gorkowski

- how badly do we need to rely on pymiescatt pkg? can we replace its functionality in house?

**Comment by Gorkowski** [comment]
I was going to chat with Benjamin at aaar, to see if he wants us to take over management of pymie or what his plans are. 

It's for the data package so we should spin that out into a particular-beta dev package

**Comment by Gorkowski** [comment]
part of particula-beta, which is in particula anymore
