### ISSUE TITLE
Inputs without units to Environment and Particle Classes are accepted  

### ISSUE THREAD

**Issue by wkchuang** [uncscode/particula#82]
Environment and Particle classes are accepting inputs without designating units.
Inputs are somehow then assigned units to pass the class tests.

**Comment by ngam** [comment]
See here: https://github.com/uncscode/particula/pull/56/files/486dcf3b97999a0dd1302c012c702b51ed3f8a70#r772012933

Not really sure how this works exactly, and so please look into it for us. It seems that it works fine with OR without the units, but that is surprising to me...

**Comment by ngam** [comment]
keep

**Comment by ngam** [comment]
This is now moot with the reorg
