### ISSUE TITLE
> * A UnitStrippedWarning pops up when running `particle_test`.

### ISSUE THREAD

**Issue by ngam** [uncscode/particula#86]
> * A UnitStrippedWarning pops up when running `particle_test`. Need help diagnosing the issue

This issue is not new, so it has nothing to do with your additions here. I do agree we need to look into it; it could be simply that `pint` doesn't play well with `numpy` in this particular case? There are a few upstream issues. Maybe worth opening this in a separate issue imo.

_Originally posted by @ngam in https://github.com/uncscode/particula/issues/84#issuecomment-1003608779_

**Comment by ngam** [comment]
We should take out the units from the `pytest.approx` call, that's all that's needed here. We didn't put units in other `pytest.approx` calls in the tests...

```python
>>> import pytest; from particula import u; type(pytest.approx(1e-12 * u.m**3 / u.s, rel=10))
.../_asarray.py:83: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  return array(a, dtype, copy=False, order=order)
<class '_pytest.python_api.ApproxNumpy'>
```

```python
>>> import pytest; from particula import u; type(pytest.approx(1e-12, rel=10))
<class '_pytest.python_api.ApproxNumpy'>
```

**Comment by wkchuang** [comment]
> We should take out the units from the `pytest.approx` call, that's all that's needed here. We didn't put units in other `pytest.approx` calls in the tests...
> 
> ```python
> >>> import pytest; from particula import u; type(pytest.approx(1e-12 * u.m**3 / u.s, rel=10))
> .../_asarray.py:83: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
>   return array(a, dtype, copy=False, order=order)
> <class '_pytest.python_api.ApproxNumpy'>
> ```
> 
> ```python
> >>> import pytest; from particula import u; type(pytest.approx(1e-12, rel=10))
> <class '_pytest.python_api.ApproxNumpy'>
> ```

Just for reference: 
On some tests, I added a `magnitude` method when calling the numbers, to avoid units. We can try separating the two checks to avoid errors: one for value, and one for units.
