### ISSUE TITLE
How does the parcel class work

### ISSUE THREAD

**Issue by Gorkowski** [uncscode/particula#92]
Can we get a basic notebook on how the parcel class works?

**Comment by ngam** [comment]
@Gorkowski could you take a moment to explain to me the need for a parcel treatment if we have a particle distribution treatment?

I am trying to understand what make a parcel its own unique thing. Is it the fact that we have a like a piece of volume moving around with particle in and out of it? Can that be achieved if we simply expanding the axes of the particle distribution to include temperature? We can also add some "exchange" rate setup or something.

**Comment by Gorkowski** [comment]
yeah, I think with our new distribution method this parcel class becomes unnecessary right now.
