### ISSUE TITLE
Unitless vectorization, for array opperations on particles

### ISSUE THREAD

**Issue by Gorkowski** [uncscode/particula#95]
vectorize the coagulation and related function calls, and make them unitless. The units can be added back later assuming things work out.

This is a prelude to tracking particle distributions by arrays.

**Comment by ngam** [comment]
@Gorkowski to help us get going, could you prepare a summary of how you envision this to work? Something like: I expect to give this module/function/class xyz inputs and have it return abc outputs. We can then fill the gaps of processes in between.

For now, we can think about it as a static problem (no time stepping). Meaning, the function could be repeated t times to accomplish t time steps if needed. Later we could implement this inside (but that will require more work).

**Comment by Gorkowski** [comment]
The outline would be something like:

particle_utilities.py 
-covers all coagulation (and sub) calculations for an array or particle radii against a single radius.
-this should also replace the calls in particle class. and you can wrap the calls with units

particle_distributions.py
holds the array distribution (radii, mass, number, density), could be a data class and not an object
This could then be saved out at each timestep.

Then something that calls both, probably a rework of the parcel class
